version: '3.11'

services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_DB_NAME=Docker_project
      - DJANGO_DB_USER=postgres
      - DJANGO_DB_PASSWORD=0200
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: Docker_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0200
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
